//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmcc.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string SiteName { get; set; }
        public string Itqf { get; set; }
        public string ItemCategory { get; set; }
        public string AcknowledgeRequired { get; set; }
        public string PreviousStatus { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<bool> IsProcess { get; set; }
        public Nullable<int> FMCCStatus { get; set; }
    }
}
