//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmcc.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public int Id { get; set; }
        public string BuildingId { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<double> GFA { get; set; }
        public Nullable<double> EUI { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<int> GreenMarkRating { get; set; }
        public string GreenMarkExpiry { get; set; }
        public string Award { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<double> AirconditionedArea { get; set; }
        public string Established { get; set; }
        public Nullable<System.DateTime> WorkingPeriodStart { get; set; }
        public Nullable<System.DateTime> WorkingPeriodEnd { get; set; }
        public Nullable<int> Status { get; set; }
        public string ImageLocation { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Lattitude { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string IPAddress { get; set; }
        public string WorkingPeriod { get; set; }
        public Nullable<double> Tariff { get; set; }
        public Nullable<int> NotificationProcess { get; set; }
        public string ChillerPlantBitmap { get; set; }
        public Nullable<double> ChwFlowDesigned { get; set; }
        public Nullable<double> CwFlowDesigned { get; set; }
        public Nullable<int> BaselineType { get; set; }
        public string OperatingFromWeekDay { get; set; }
        public string OperatingToWeekDay { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public Nullable<int> BedNo { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> ContractCapacity { get; set; }
    }
}
