//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmcc.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CO2EmissionFactor
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> RecordDateTime { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> AverageOperatingMargin { get; set; }
        public Nullable<decimal> BuildMargin { get; set; }
        public string CombinedMargin { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
