//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmcc.Models.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardMenuPreset
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> UserFkId { get; set; }
        public string MenuId { get; set; }
        public Nullable<int> MenuFkId { get; set; }
        public string BlockId { get; set; }
        public Nullable<int> BlockFkId { get; set; }
        public string BlockText { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> ObjectFkId { get; set; }
        public string ObjectText { get; set; }
        public string DataFieldId { get; set; }
        public Nullable<int> DataFieldFkId { get; set; }
        public string DataFieldText { get; set; }
        public string DateFlag { get; set; }
        public string DateFlagText { get; set; }
        public string ChartType { get; set; }
        public string ChartTypeText { get; set; }
        public Nullable<int> Order { get; set; }
        public string DisplayProfile { get; set; }
        public string ObjectToCompareId { get; set; }
        public string ObjectToCompareText { get; set; }
        public string DataFieldToCompareId { get; set; }
        public string DataFieldToCompareText { get; set; }
        public string ChartTitle { get; set; }
        public string RATemperature { get; set; }
        public string ValveOutput { get; set; }
        public Nullable<double> ThresholdRangeFrom { get; set; }
        public Nullable<double> ThresholdRangeTo { get; set; }
        public Nullable<double> TemperatureSetPoint { get; set; }
    }
}
