//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fmcc.Models.EntityDataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FMCCDataContext : DbContext
    {
        public FMCCDataContext()
            : base("name=FMCCDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alarm> Alarms { get; set; }
        public virtual DbSet<AlarmStatu> AlarmStatus { get; set; }
        public virtual DbSet<AlarmSupress> AlarmSupresses { get; set; }
        public virtual DbSet<Alert> Alerts { get; set; }
        public virtual DbSet<AlertAverageSetup> AlertAverageSetups { get; set; }
        public virtual DbSet<AlertData> AlertDatas { get; set; }
        public virtual DbSet<AlertNotifyUser> AlertNotifyUsers { get; set; }
        public virtual DbSet<AlertRuleSetup> AlertRuleSetups { get; set; }
        public virtual DbSet<AlertSuppress> AlertSuppresses { get; set; }
        public virtual DbSet<Building> Buildings { get; set; }
        public virtual DbSet<BuildingAlarmForward> BuildingAlarmForwards { get; set; }
        public virtual DbSet<BuildingObjectData> BuildingObjectDatas { get; set; }
        public virtual DbSet<BuildingUser> BuildingUsers { get; set; }
        public virtual DbSet<DashboardMenu> DashboardMenus { get; set; }
        public virtual DbSet<DashboardMenuPreset> DashboardMenuPresets { get; set; }
        public virtual DbSet<DataField> DataFields { get; set; }
        public virtual DbSet<DataFieldUnit> DataFieldUnits { get; set; }
        public virtual DbSet<Expression> Expressions { get; set; }
        public virtual DbSet<ItqfReplacement> ItqfReplacements { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuAuthentication> MenuAuthentications { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<Object> Objects { get; set; }
        public virtual DbSet<ObjectOnOffMapping> ObjectOnOffMappings { get; set; }
        public virtual DbSet<ObjectUnitMapping> ObjectUnitMappings { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<TempReading> TempReadings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserLog> UserLogs { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Site> Sites { get; set; }
        public virtual DbSet<BuildingType> BuildingTypes { get; set; }
        public virtual DbSet<PowerMonthlyTariff> PowerMonthlyTariffs { get; set; }
        public virtual DbSet<CO2EmissionFactor> CO2EmissionFactor { get; set; }
    }
}
